#############################################################################
# Makefile for building: glpicture
# Generated by qmake (2.01a) (Qt 4.5.1) on: Mon Dec 21 05:21:18 2009
# Project:  glpicture.pro
# Template: app
# Command: /home/student/qtsdk-2009.02/qt/bin/qmake -spec ../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile glpicture.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qtsdk-2009.02/qt/mkspecs/linux-g++ -I. -I../qtsdk-2009.02/qt/include/QtCore -I../qtsdk-2009.02/qt/include/QtNetwork -I../qtsdk-2009.02/qt/include/QtGui -I../qtsdk-2009.02/qt/include/QtOpenGL -I../qtsdk-2009.02/qt/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/student/qtsdk-2009.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/student/qtsdk-2009.02/qt/lib -L/usr/X11R6/lib -lQtOpenGL -L/home/student/qtsdk-2009.02/qt/lib -L/usr/X11R6/lib -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lQtGui -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/student/qtsdk-2009.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		pmd1.cpp \
		pmd2.cpp \
		pmd3.cpp \
		pmd4.cpp moc_dialog.cpp \
		moc_pmd1.cpp \
		moc_pmd2.cpp \
		moc_pmd3.cpp \
		moc_pmd4.cpp
OBJECTS       = main.o \
		dialog.o \
		pmd1.o \
		pmd2.o \
		pmd3.o \
		pmd4.o \
		moc_dialog.o \
		moc_pmd1.o \
		moc_pmd2.o \
		moc_pmd3.o \
		moc_pmd4.o
DIST          = ../qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		../qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.02/qt/mkspecs/features/unix/opengl.prf \
		../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		glpicture.pro
QMAKE_TARGET  = glpicture
DESTDIR       = 
TARGET        = glpicture

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: glpicture.pro  ../qtsdk-2009.02/qt/mkspecs/linux-g++/qmake.conf ../qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		../qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.02/qt/mkspecs/features/unix/opengl.prf \
		../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		/home/student/qtsdk-2009.02/qt/lib/libQtOpenGL.prl \
		/home/student/qtsdk-2009.02/qt/lib/libQtGui.prl \
		/home/student/qtsdk-2009.02/qt/lib/libQtCore.prl \
		/home/student/qtsdk-2009.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile glpicture.pro
../qtsdk-2009.02/qt/mkspecs/common/g++.conf:
../qtsdk-2009.02/qt/mkspecs/common/unix.conf:
../qtsdk-2009.02/qt/mkspecs/common/linux.conf:
../qtsdk-2009.02/qt/mkspecs/qconfig.pri:
../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
../qtsdk-2009.02/qt/mkspecs/features/debug.prf:
../qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
../qtsdk-2009.02/qt/mkspecs/features/qt.prf:
../qtsdk-2009.02/qt/mkspecs/features/unix/opengl.prf:
../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
../qtsdk-2009.02/qt/mkspecs/features/moc.prf:
../qtsdk-2009.02/qt/mkspecs/features/resources.prf:
../qtsdk-2009.02/qt/mkspecs/features/uic.prf:
../qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
../qtsdk-2009.02/qt/mkspecs/features/lex.prf:
../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf:
/home/student/qtsdk-2009.02/qt/lib/libQtOpenGL.prl:
/home/student/qtsdk-2009.02/qt/lib/libQtGui.prl:
/home/student/qtsdk-2009.02/qt/lib/libQtCore.prl:
/home/student/qtsdk-2009.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile glpicture.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/glpicture1.0.0 || $(MKDIR) .tmp/glpicture1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/glpicture1.0.0/ && $(COPY_FILE) --parents dialog.h FORMS += dialog.ui pmd1.h pmd2.h pmd3.h pmd4.h .tmp/glpicture1.0.0/ && $(COPY_FILE) --parents main.cpp dialog.cpp pmd1.cpp pmd2.cpp pmd3.cpp pmd4.cpp .tmp/glpicture1.0.0/ && (cd `dirname .tmp/glpicture1.0.0` && $(TAR) glpicture1.0.0.tar glpicture1.0.0 && $(COMPRESS) glpicture1.0.0.tar) && $(MOVE) `dirname .tmp/glpicture1.0.0`/glpicture1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/glpicture1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_pmd1.cpp moc_pmd2.cpp moc_pmd3.cpp moc_pmd4.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_pmd1.cpp moc_pmd2.cpp moc_pmd3.cpp moc_pmd4.cpp
moc_dialog.cpp: pmd1.h \
		pmd2.h \
		pmd3.h \
		pmd4.h \
		dialog.h
	/home/student/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_pmd1.cpp: pmd1.h
	/home/student/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) pmd1.h -o moc_pmd1.cpp

moc_pmd2.cpp: pmd2.h
	/home/student/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) pmd2.h -o moc_pmd2.cpp

moc_pmd3.cpp: pmd3.h
	/home/student/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) pmd3.h -o moc_pmd3.cpp

moc_pmd4.cpp: pmd4.h
	/home/student/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) pmd4.h -o moc_pmd4.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp dialog.h \
		pmd1.h \
		pmd2.h \
		pmd3.h \
		pmd4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		pmd1.h \
		pmd2.h \
		pmd3.h \
		pmd4.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

pmd1.o: pmd1.cpp pmd1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmd1.o pmd1.cpp

pmd2.o: pmd2.cpp pmd2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmd2.o pmd2.cpp

pmd3.o: pmd3.cpp pmd3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmd3.o pmd3.cpp

pmd4.o: pmd4.cpp pmd4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmd4.o pmd4.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_pmd1.o: moc_pmd1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pmd1.o moc_pmd1.cpp

moc_pmd2.o: moc_pmd2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pmd2.o moc_pmd2.cpp

moc_pmd3.o: moc_pmd3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pmd3.o moc_pmd3.cpp

moc_pmd4.o: moc_pmd4.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pmd4.o moc_pmd4.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

